CREATE DATABASE E_Commerce_Sales_Analytics;
USE E_Commerce_Sales_Analytics;

SELECT * FROM customer_behavior;

#1. Retrieve all customer purchase records:
CREATE VIEW Customer_Purchase_Records AS
SELECT *
FROM customer_behavior;

#1. Retrieve all customer purchase records:
SELECT * FROM Customer_Purchase_Records;


#2. Calculate the total revenue generated by each product category:
CREATE VIEW Revenue_By_Category AS
SELECT Category,
       SUM(Purchase_Amount) AS Total_Revenue
FROM customer_behavior
GROUP BY Category;

#2. Calculate the total revenue generated by each product category:
SELECT * FROM Revenue_By_Category;


#3. Find the average purchase amount for each gender:
CREATE VIEW Average_Purchase_By_Gender AS
SELECT Gender,
       ROUND(AVG(Purchase_Amount),2) AS Average_Purchase
FROM customer_behavior
GROUP BY Gender;

#3. Find the average purchase amount for each gender:
SELECT * FROM Average_Purchase_By_Gender;


#4. Identify the top 5 customers based on total purchase amount:
CREATE VIEW Top_5_Customers AS
SELECT Customer_ID,
       SUM(Purchase_Amount) AS Total_Spent
FROM customer_behavior
GROUP BY Customer_ID
ORDER BY Total_Spent DESC
LIMIT 5;

#4. Identify the top 5 customers based on total purchase amount:
SELECT * FROM Top_5_Customers;


#5. Calculate the number of customers in each age group:
CREATE VIEW Customers_By_Age_Group AS
SELECT Age_Group,
       COUNT(Customer_ID) AS Total_Customers
FROM customer_behavior
GROUP BY Age_Group;

#5. Calculate the number of customers in each age group:
SELECT * FROM Customers_By_Age_Group;


#6. Find the average review rating for each product category:
CREATE VIEW Average_Rating_By_Category AS
SELECT Category,
       ROUND(AVG(Review_Rating),2) AS Average_Rating
FROM customer_behavior
GROUP BY Category;

#6. Find the average review rating for each product category:
SELECT * FROM Average_Rating_By_Category;


#7. Calculate the total revenue generated through each payment method:
CREATE VIEW Revenue_By_Payment_Method AS
SELECT Payment_Method,
       SUM(Purchase_Amount) AS Total_Revenue
FROM customer_behavior
GROUP BY Payment_Method;

#7. Calculate the total revenue generated through each payment method:
SELECT * FROM Revenue_By_Payment_Method;


#8. Find the number of customers with and without a subscription:
CREATE VIEW Subscription_Status AS
SELECT Subscription_Status,
       COUNT(Customer_ID) AS Total_Customers
FROM customer_behavior
GROUP BY Subscription_Status;

#8. Find the number of customers with and without a subscription:
SELECT * FROM Subscription_Status;


#9. Calculate the average purchase amount for each shipping type:
CREATE VIEW Average_Purchase_By_Shipping AS
SELECT Shipping_Type,
       ROUND(AVG(Purchase_Amount),2) AS Average_Purchase
FROM customer_behavior
GROUP BY Shipping_Type;

#9. Calculate the average purchase amount for each shipping type:
SELECT * FROM Average_Purchase_By_Shipping;


#10. Find the most frequently purchased product category:
CREATE VIEW Most_Purchased_Category AS
SELECT Category,
       COUNT(*) AS Total_Orders
FROM customer_behavior
GROUP BY Category
ORDER BY Total_Orders DESC
LIMIT 1;

#10. Find the most frequently purchased product category:
SELECT * FROM Most_Purchased_Category;


#11. Calculate the average purchase amount for each season:
CREATE VIEW Average_Purchase_By_Season AS
SELECT Season,
       ROUND(AVG(Purchase_Amount),2) AS Average_Purchase
FROM customer_behavior
GROUP BY Season;

#11. Calculate the average purchase amount for each season:
SELECT * FROM Average_Purchase_By_Season;


#12. Find the top 5 locations with the highest revenue:
CREATE VIEW Top_5_Locations AS
SELECT Location,
       SUM(Purchase_Amount) AS Total_Revenue
FROM customer_behavior
GROUP BY Location
ORDER BY Total_Revenue DESC
LIMIT 5;

#12. Find the top 5 locations with the highest revenue:
SELECT * FROM Top_5_Locations;


#13. Calculate the total revenue generated by subscribed customers:
CREATE VIEW Revenue_By_Subscription AS
SELECT Subscription_Status,
       SUM(Purchase_Amount) AS Total_Revenue
FROM customer_behavior
GROUP BY Subscription_Status;

#13. Calculate the total revenue generated by subscribed customers:
SELECT * FROM Revenue_By_Subscription;


#14. Find the average purchase amount based on discount availability:
CREATE VIEW Average_Purchase_By_Discount AS
SELECT Discount_Applied,
       ROUND(AVG(Purchase_Amount),2) AS Average_Purchase
FROM customer_behavior
GROUP BY Discount_Applied;

#14. Find the average purchase amount based on discount availability:
SELECT * FROM Average_Purchase_By_Discount;


#15. Retrieve customers who have made more than 20 previous purchases:
CREATE VIEW Frequent_Customers AS
SELECT Customer_ID,
       Previous_Purchases,
       Purchase_Amount
FROM customer_behavior
WHERE Previous_Purchases > 20;

#15. Retrieve customers who have made more than 20 previous purchases:
SELECT * FROM Frequent_Customers;